name: scheduled-test
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Notify failed scheduled test
        if: failed()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
           ⚠️ Scheduled test failed. Please fix! 🔧

           Repository: ${{ github.repository }}